= レポート
:allow-uri-read: 




=== レポート

ランドスケープの分析に役立つレポートを生成してダウンロードできるようになりました。事前に設計されたレポートでは、フェイルオーバーとフェイルバックの概要、すべてのサイトのレプリケーションの詳細、過去 7 日間のジョブの詳細が表示されます。

参照 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/reports.html["災害復旧レポートを作成する"]。



=== 30日間無料トライアル

NetApp Disaster Recovery の 30 日間無料トライアルに今すぐサインアップできます。以前は、無料トライアルは 90 日間でした。

参照 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["ライセンスの設定"]。



=== レプリケーションプランの無効化と有効化

以前のリリースには、日次および週次スケジュールをサポートするために必要だったフェールオーバー テスト スケジュール構造の更新が含まれていました。この更新では、新しい毎日および毎週のフェールオーバー テスト スケジュールを使用できるように、既存のすべてのレプリケーション プランを無効にしてから再度有効にする必要がありました。これは 1 回限りの要件です。

方法は次のとおりです。

. メニューから*レプリケーション プラン*を選択します。
. プランを選択し、アクション アイコンを選択してドロップダウン メニューを表示します。
. *無効*を選択します。
. 数分後、「*有効*」を選択します。




=== フォルダマッピング

レプリケーション プランを作成し、コンピューティング リソースをマップするときに、データセンター、クラスター、ホストに指定したフォルダーに VM が回復されるようにフォルダーをマップできるようになりました。

詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"] 。



=== フェイルオーバー、フェイルバック、テストフェイルオーバーに利用可能な VM の詳細

障害が発生し、フェイルオーバーを開始したり、フェイルバックを実行したり、フェイルオーバーをテストしたりするときに、VM の詳細を表示して、再起動しなかった VM を特定できるようになりました。

参照 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["アプリケーションをリモートサイトにフェイルオーバーする"]。



=== 順序付けられたブートシーケンスによる VM ブート遅延

レプリケーション プランを作成するときに、プラン内の各 VM のブート遅延を設定できるようになりました。これにより、VM の起動シーケンスを設定して、後続の優先度の VM が起動される前に、優先度 1 の VM がすべて実行されていることを確認できます。

詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"] 。



=== VM オペレーティング システム情報

レプリケーション プランを作成すると、プラン内の各 VM のオペレーティング システムを確認できるようになりました。これは、VM をリソース グループにグループ化する方法を決定するのに役立ちます。

詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"] 。



=== VM名のエイリアシング

レプリケーション プランを作成するときに、災害復旧サイトの VM 名にプレフィックスとサフィックスを追加できるようになりました。これにより、プラン内の VM に、より説明的な名前を使用できるようになります。

詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"] 。



=== 古いスナップショットをクリーンアップする

指定した保持数を超えて不要になったスナップショットは削除できます。スナップショットの保持数を減らすと、時間の経過とともにスナップショットが蓄積される可能性があります。これで、スナップショットを削除してスペースを解放できます。これは、オンデマンドでいつでも、またはレプリケーション プランを削除するときに実行できます。

詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["サイト、リソース グループ、レプリケーション プラン、データストア、仮想マシンの情報の管理"] 。



=== スナップショットを調整する

ソースとターゲット間で同期されていないスナップショットを調整できるようになりました。これは、NetApp Disaster Recovery の外部のターゲットでスナップショットが削除された場合に発生する可能性があります。サービスは、ソース上のスナップショットを 24 時間ごとに自動的に削除します。ただし、これをオンデマンドで実行できます。この機能により、すべてのサイト間でスナップショットの一貫性を確保できます。

詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["レプリケーションプランの管理"] 。
