= サブネットマッピング
:allow-uri-read: 




=== サブネットマッピング

このリリースでは、サブネット マッピングを使用してフェイルオーバー時の IP アドレスを新しい方法で管理できるようになり、vCenter ごとにサブネットを追加できるようになりました。これを実行すると、各仮想ネットワークの IPv4 CIDR、デフォルト ゲートウェイ、および DNS が定義されます。

フェイルオーバー時に、 NetApp Disaster Recovery は、マッピングされた仮想ネットワークに提供された CIDR を調べて各 vNIC の適切な IP アドレスを決定し、それを使用して新しい IP アドレスを導出します。

例えば：

* ネットワークA = 10.1.1.0/24
* ネットワークB = 192.168.1.0/24


VM1 には、NetworkA に接続された vNIC (10.1.1.50) があります。レプリケーション プラン設定では、NetworkA は NetworkB にマップされます。

フェイルオーバー時に、 NetApp Disaster Recovery は元の IP アドレス (10.1.1) のネットワーク部分を置き換え、元の IP アドレス (10.1.1.50) のホスト アドレス (.50) を保持します。 VM1 の場合、 NetApp Disaster Recovery はNetworkB の CIDR 設定を確認し、NetworkB のネットワーク部分 192.168.1 を使用し、ホスト部分 (.50) を保持して VM1 の新しい IP アドレスを作成します。新しい IP は 192.168.1.50 になります。

要約すると、ホスト アドレスは同じままですが、ネットワーク アドレスはサイトのサブネット マッピングで構成されているものに置き換えられます。これにより、特に数百のネットワークと数千の VM を管理する場合に、フェイルオーバー時の IP アドレスの再割り当てをより簡単に管理できるようになります。

サイトにサブネットマッピングを含める方法の詳細については、以下を参照してください。 https://docs.netapp.com/us-en/data-services-disaster-recovery/use/sites-add.html["vCenter Server サイトを追加する"] 。



=== スキップ保護

レプリケーション プランのフェイルオーバー後にサービスが自動的に逆保護関係を作成しないように、保護をスキップできるようになりました。これは、NetApp Disaster Recovery内でサイトをオンラインに戻す前に、復元されたサイトで追加の操作を実行する場合に役立ちます。

フェールオーバーを開始すると、元のソース サイトがオンラインの場合、デフォルトでは、サービスによってレプリケーション プラン内の各ボリュームに対して逆方向の保護関係が自動的に作成されます。これは、サービスがターゲット サイトからソース サイトへのSnapMirror関係を作成することを意味します。また、フェイルバックを開始すると、このサービスはSnapMirror関係を自動的に元に戻します。

フェイルオーバーを開始するときに、*保護をスキップ*オプションを選択できるようになりました。これにより、サービスはSnapMirror関係を自動的に逆転させなくなります。代わりに、レプリケーション プランの両側に書き込み可能なボリュームを残します。

元のソース サイトがオンラインに戻った後、レプリケーション プランの [アクション] メニューから [*リソースの保護*] を選択して、逆方向の保護を確立できます。これにより、プラン内の各ボリュームに対して逆方向のレプリケーション関係を作成しようとします。保護が復元されるまで、このジョブを繰り返し実行できます。保護が復元されると、通常の方法でフェイルバックを開始できます。

スキップ保護の詳細については、 https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["アプリケーションをリモートサイトにフェイルオーバーする"] 。



=== SnapMirrorはレプリケーションプランで更新をスケジュールします

NetApp Disaster Recovery、ネイティブのONTAP SnapMirrorポリシー スケジューラやONTAPとのサードパーティ統合などの外部スナップショット管理ソリューションの使用がサポートされるようになりました。レプリケーション プラン内のすべてのデータストア (ボリューム) に、別の場所で管理されているSnapMirror関係がすでに存在する場合は、それらのスナップショットをNetApp Disaster Recoveryのリカバリ ポイントとして使用できます。

設定するには、レプリケーション プラン > リソース マッピング セクションで、データストア マッピングを設定するときに *プラットフォーム管理のバックアップと保持スケジュールを使用する* チェックボックスをオンにします。

このオプションを選択すると、 NetApp Disaster Recovery はバックアップ スケジュールを構成しません。ただし、テスト、フェイルオーバー、フェイルバック操作のためにスナップショットが作成される可能性があるため、保持スケジュールを構成する必要があります。

これが構成されると、サービスは定期的にスケジュールされたスナップショットを取得せず、代わりに外部エンティティに依存してスナップショットを取得および更新します。

レプリケーションプランで外部スナップショットソリューションを使用する方法の詳細については、以下を参照してください。 https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"] 。
