= VMのスケジュールされた検出
:allow-uri-read: 




=== VMのスケジュールされた検出

NetApp Disaster Recovery は 24 時間ごとに検出を実行します。このリリースでは、ニーズに合わせて検出スケジュールをカスタマイズし、必要なときにパフォーマンスへの影響を軽減できるようになりました。たとえば、多数の VM がある場合は、検出スケジュールを 48 時間ごとに実行するように設定できます。  VM の数が少ない場合は、検出スケジュールを 12 時間ごとに実行するように設定できます。

検出をスケジュールしたくない場合は、スケジュールされた検出オプションを無効にして、いつでも手動で検出を更新できます。

詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["vCenter Server サイトを追加する"] 。



=== リソース グループ データストアのサポート

以前は、VM ごとにのみリソース グループを作成できました。このリリースでは、データストアごとにリソース グループを作成できるようになりました。レプリケーション プランを作成し、そのプランのリソース グループを作成すると、データストア内のすべての VM が一覧表示されます。これは、多数の VM があり、それらをデータストアごとにグループ化したい場合に便利です。

次の方法で、データストアを含むリソース グループを作成できます。

* データストアを使用してリソース グループを追加する場合は、データストアの一覧を表示できます。  1 つ以上のデータストアを選択してリソース グループを作成できます。
* レプリケーション プランを作成し、プラン内にリソース グループを作成すると、データストア内の VM を確認できます。


詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"] 。



=== 無料トライアルまたはライセンスの有効期限の通知

このリリースでは、ライセンスを取得する時間を確保するために、無料トライアルが 60 日後に期限切れになることを通知します。このリリースでは、ライセンスの有効期限が切れる日に通知も提供されます。



=== サービス更新の通知

このリリースでは、サービスがアップグレードされ、メンテナンス モードになっていることを示すバナーが上部に表示されます。バナーは、サービスのアップグレード中に表示され、アップグレードが完了すると消えます。アップグレードの進行中も UI での作業は続行できますが、新しいジョブを送信することはできません。更新が完了し、サービスが本番モードに戻った後に、スケジュールされたジョブが実行されます。
