= BlueXP disaster recoveryはNetApp Disaster Recoveryになりました
:allow-uri-read: 




[[bluexp-disaster-recovery-is-now-netapp-disaster-recovery]]
=== BlueXP disaster recoveryはNetApp Disaster Recoveryになりました

BlueXP disaster recoveryはNetApp Disaster Recoveryに名前が変更されました。



[[bluexp-is-now-netapp-console]]
=== BlueXPはNetApp Consoleになりました

NetApp Console は、強化および再構築された BlueXP 基盤の上に構築されており、オンプレミスおよびクラウド環境全体にわたって、エンタープライズグレードで NetApp ストレージと NetApp Data Services の一元管理を提供します。リアルタイムのインサイト、より迅速なワークフロー、簡素化された管理を実現し、高度なセキュリティとコンプライアンスを備えています。

変更内容の詳細については、 link:https://docs.netapp.com/us-en/console-relnotes/index.html["NetApp Consoleのリリースノート"]。



[[other-updates]]
=== その他のアップデート

* Amazon FSx for NetApp ONTAPを使用した Amazon Elastic VMware Service (EVS) のサポートはパブリックプレビュー段階です。このリリースにより、一般公開されました。詳細については、link:../reference/evs-deploy-guide-introduction.html["Amazon Elastic VMware Service とAmazon FSx for NetApp ONTAPを使用したNetApp Disaster Recoveryの紹介"] 。
* オンプレミス展開での検出時間の短縮を含む、ストレージ検出の改善
* ロールベースのアクセス制御（RBAC）や強化されたユーザー権限を含む、アイデンティティおよびアクセス管理（IAM）のサポート
* Azure VMware ソリューションとCloud Volumes ONTAPのプライベート プレビュー サポート。このサポートにより、 Cloud Volumes ONTAPストレージを使用して、オンプレミスから Azure VMware ソリューションへのディザスター リカバリー保護を構成できるようになりました。

