= レプリケーションプランからデータストアを除外する
:allow-uri-read: 




[[exclude-a-datastore-from-replication-plans]]
=== レプリケーションプランからデータストアを除外する

ディザスターリカバリーでレプリケーションプランを作成する際に、特定のデータストアをレプリケーション対象から除外できるようになりました。VMが複数のデータストアを使用するように構成されている場合、レプリケートするデータストアを制限できます。

詳細については、link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"^]を参照してください。



[[removed-password-validation-from-vcenter-password]]
=== vCenter パスワードからパスワード検証を削除

ディザスタリカバリでは、vCenter パスワードのパスワード制限が削除され、スペースを含むパスワードが許可されるようになりました。

詳細については、link:https://docs.netapp.com/us-en/data-services-disaster-recovery/reference/evs-deploy-guide-add-vcenters.html["NetApp Disaster Recoveryにオンプレミスおよび Amazon EVS vCenter クラスターを追加する"^]を参照してください。



[[new-replication-plan-submenu]]
=== 新しいレプリケーションプランのサブメニュー

ディザスターリカバリーに、レプリケーションプランのダッシュボードから vCenter の更新をトリガーする新しいメニューオプションが追加されました。レプリケーションプランダッシュボードのアクションメニューからサブメニューにアクセスできます。**プランの健全性**を選択し、次に**ソース vCenter の更新 / ターゲット vCenter の更新**を選択してください。

詳細については、link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html#modify-a-replication-plan["レプリケーションプランを変更する"^]を参照してください。



[[improved-network-discovery]]
=== ネットワーク検出の改善

ディザスタリカバリには、より幅広いネットワーク構成をサポートするために、改善されたネットワーク検出が含まれるようになりました。
