= オンプレミス環境での複数のコンソール エージェントのサポート
:allow-uri-read: 




=== オンプレミス環境での複数のコンソール エージェントのサポート

オンプレミスでDisaster Recovery を使用している場合は、vCenter インスタンスごとにコンソール エージェントを展開して、回復力を向上させることができます。

たとえば、2 つのサイト (サイト A とサイト B) がある場合、サイト A には、vCenter 1、 ONTAPデプロイメント 1、およびONTAPデプロイメント 2 に接続されたコンソール エージェント A を配置できます。サイト B には、vCenter 2 とONTAPデプロイメント 3 および 4 に接続されたコンソール エージェント B を配置できます。

災害復旧のコンソールエージェントの詳細については、以下を参照してください。 link:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/dr-prerequisites.html#netapp-console-prerequisites["コンソールエージェントを作成する"^]。



=== データストアベースの保護を使用したレプリケーション プランのフェイルオーバー後に VM を追加する

フェイルオーバーがトリガーされると、データストアベースの保護を使用するすべてのレプリケーション プランには、データストアに追加された VM が含まれます (検出された場合)。フェイルオーバーが完了する前に、追加された VM のマッピングの詳細を提供する必要があります。

詳細については、 link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["フェイルオーバーアプリケーション"^]。



=== 新しいメール通知

災害復旧では、次のイベントに関する電子メール通知が提供されるようになりました。

* 容量使用制限に近づいています
* レポート生成が完了しました
* 仕事の失敗
* ライセンスの有効期限または違反




=== Swaggerの改善

これで、Disaster Recovery 内から Swagger ドキュメントにアクセスできるようになりました。災害復旧で、**設定** を選択し、次に **API ドキュメント** を選択して Swagger にリンクするか、ブラウザのシークレット/プライベート モードで次の URL にアクセスします。 link:https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas"^]。



=== 改善されたユーザーインターフェース

災害復旧では、警告とエラー解決が改善されました。このリリースでは、キャンセルされたジョブがユーザー インターフェイスに表示されないエラーが修正されました。キャンセルされたジョブが表示されるようになりました。同じ宛先ネットワークが複数の異なるソース ネットワークにマップされている場合にも、新しい警告が表示されます。



=== レプリケーション プランに VM フォルダ構造の保持がデフォルトとして追加されました

レプリケーションを作成すると、新しいデフォルトでは VM フォルダー構造が保持されます。リカバリ対象に元のフォルダ階層がない場合、Disaster Recovery によってそれが作成されます。このオプションを選択解除すると、元のフォルダー階層を無視できます。

詳細については、 link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"^]。
