---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-introduction.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, netapp, ontap 
summary: Amazon EVS とAmazon FSx for NetApp ONTAPを使用したNetApp Disaster Recoveryの紹介。 
---
= Amazon Elastic VMware Service と Amazon FSx for NetApp ONTAP を使用した NetApp Disaster Recovery について学ぶ
:allow-uri-read: 


[role="lead"]
NetApp Disaster Recovery は、オンプレミス環境から Amazon EVS および Amazon FSx for NetApp ONTAP にデータをレプリケートすることで、VMware ワークロードをディザスタリカバリから保護します。

あらゆる DR ソリューションの主な課題の 1 つは、DR レプリケーションおよびリカバリ インフラストラクチャを提供するためだけに、追加のコンピューティング、ネットワーク、およびストレージ リソースを購入、構成、維持するための増分コストを管理することです。重要なオンプレミスの仮想リソースを保護するための一般的なオプションの 1 つは、クラウドでホストされる仮想リソースを DR レプリケーションおよびリカバリ インフラストラクチャとして使用することです。  Amazon は、 NetApp ONTAPがホストする VM インフラストラクチャと互換性のあるコスト効率の高いリソースを提供できるソリューションの一例です。

Amazonは、仮想プライベートクラウド（VPC）内でVMware Cloud Foundationを利用できるようにするAmazon Elastic VMware Service（Amazon EVS）を発表しました。Amazon EVSは、使い慣れたVMwareソフトウェアとツールに加え、AWSの回復力とパフォーマンスを提供し、Amazon EVS のvCentersがオンプレミスの仮想化インフラと統合できるようにします。

Amazon EVSにはストレージリソースが付属していますが、ネイティブストレージを使用すると、ストレージ負荷の高いワークロードを抱える組織ではその効果が低下する可能性があります。このような場合、Amazon EVS と Amazon FSx for NetApp ONTAP ストレージ（Amazon FSxN）を組み合わせることで、より柔軟なストレージソリューションを提供できます。さらに、オンプレミスで NetApp ONTAP ストレージソリューションを使用して VMware インフラをホストしている場合、Amazon EVS と FSx for ONTAP を併用することで、オンプレミス環境とクラウド環境にわたるデータ相互運用性と保護機能を利用できます。

Amazon FSx for NetApp ONTAPの詳細については、以下を参照してください。 https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Amazon FSx for NetApp ONTAPを使い始める"^] 。
