---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-install-connector.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: NetApp Console エージェントは、NetApp Console とクラウドまたはオンプレミスのストレージリソース間の接続と管理を調整します。 
---
= NetApp Disaster Recovery用のNetApp Consoleエージェントをインストールする
:allow-uri-read: 


[role="lead"]
NetApp Console エージェントを使用すると、NetApp Console の導入をインフラストラクチャに接続して、AWS、Azure、Google Cloud、またはオンプレミス環境全体でソリューションを安全にオーケストレーションできます。Console エージェントは、NetApp Console がデータインフラストラクチャを管理するために実行する必要があるアクションを実行します。Console エージェントは、NetApp Disaster Recovery の SaaS レイヤーを常にポーリングして、実行する必要があるアクションを確認します。

NetApp Disaster Recoveryでは、実行されるアクションは、各サービスのネイティブAPIを使用してVMware vCenterクラスタとONTAPストレージインスタンスをオーケストレーションし、オンプレミスの場所で実行されている本番VMを保護します。Console agentはネットワーク上の任意の場所にインストールできますが、NetApp Disaster Recoveryの災害復旧サイトにConsole agentをインストールすることをお勧めします。DRサイトにインストールすることで、プライマリサイトに障害が発生した場合でも、NetApp Console UIはConsole agentへの接続を維持し、そのDRサイト内でリカバリプロセスをオーケストレーションできます。



== インストール

* Disaster Recoveryを使用するには、Consoleエージェントを標準モードでインストールします。Consoleエージェントのインストールの種類の詳細については、 https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["NetApp Console の導入モードについて"^]を参照してください。


コンソールエージェントの具体的なインストール手順は、導入タイプによって異なります。詳細については、link:https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["コンソールエージェントについて学ぶ"^]を参照してください。


TIP: Amazon AWS を使用して Console エージェントをインストールする最も簡単な方法は、AWS Marketplace を使用することです。AWS Marketplace を使用した Console エージェントのインストールの詳細については、 https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-aws-marketplace.html["AWS MarketplaceからConsoleエージェントを作成する"^]を参照してください。
