---
sidebar: sidebar 
permalink: reference/vcenter-privileges.html 
keywords: disaster recovery, bluexp, vcenter, 
summary: 'NetApp Disaster Recovery がデータストアの登録と登録解除、VM の起動と停止、仮想マシン (VM) の再構成などのサービスを実行できるようにするには、vCenter アカウントに最低限の vCenter 権限が必要です。次の表には、NetApp Disaster Recovery がvCenter クラスタとインターフェースするために必要なすべての権限がリストされています。' 
---
= NetApp Disaster Recoveryに必要な vCenter 権限
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
NetApp Disaster Recovery がデータストアの登録と登録解除、VM の起動と停止、仮想マシン (VM) の再構成などのサービスを実行できるようにするには、vCenter アカウントに最低限の vCenter 権限が必要です。次の表には、NetApp Disaster Recovery がvCenter クラスタとインターフェースするために必要なすべての権限がリストされています。

[cols="25,35a,40a"]
|===
| タイプ | 権限名 | 説明 


| *データストア*  a| 
データストア.データストアを構成する
 a| 
データストアを構成するために使用します。



|   a| 
データストア.データストアを削除
 a| 
データストアを削除するために使用します。



| *仮想マシン*  a| 
仮想マシン.構成.設定の変更
 a| 
一般的な VM 設定を変更するために使用します。



|   a| 
仮想マシン.構成.デバイス設定の変更
 a| 
既存のデバイスのプロパティを変更するために使用します。



|   a| 
仮想マシン.構成.パスからの再読み込み
 a| 
VM の ID を保持しながら VM 構成パッチを変更するために使用します。  VMware vCenter Site Recovery Manager などのソリューションは、この操作を使用して、フェイルオーバーおよびフェイルバック中に VM の識別を維持します。



|   a| 
仮想マシン.構成.名前の変更
 a| 
VM の名前を変更したり、VM に関連付けられたノードを変更したりするために使用します。



|   a| 
仮想マシン.構成.ゲスト情報をリセット
 a| 
VM のゲスト オペレーティング システム情報を編集するために使用します。



|   a| 
仮想マシン.構成.メモリの変更
 a| 
VM に割り当てられるメモリの量を変更するために使用します。



|   a| 
仮想マシン.構成.CPU数の変更
 a| 
仮想 CPU の数を変更するために使用します。



| *仮想マシンゲスト*  a| 
仮想マシン.ゲスト操作.ゲスト操作の変更
 a| 
VM へのファイルの転送など、VM 内のゲスト オペレーティング システムの変更を伴う VM ゲスト操作を有効にします。



| *仮想マシンの相互作用*  a| 
仮想マシン.インタラクション.電源オフ
 a| 
電源がオンになっている VM の電源をオフにするために使用します。この操作により、ゲスト オペレーティング システムの電源がオフになります。



|   a| 
仮想マシン.インタラクション.電源オン
 a| 
電源がオフになっている VM の電源をオンにし、一時停止されている VM を再開するために使用します。



|   a| 
仮想マシン.相互作用.VMware Toolsのインストール
 a| 
VMware Tools CD インストーラをゲスト オペレーティング システムの CD-ROM としてマウントおよびアンマウントするために使用します。



| *仮想マシンインベントリ*  a| 
仮想マシン.インベントリ.新規作成
 a| 
VM を作成し、その実行のためのリソースを割り当てるために使用します。



|   a| 
仮想マシン.インベントリ.登録
 a| 
既存の VM を vCenter Server またはホスト インベントリに追加するために使用します。



|   a| 
仮想マシン.インベントリ.登録解除
 a| 
vCenter Server またはホスト インベントリから VM を登録解除するために使用します。



| *仮想マシンの状態*  a| 
仮想マシン。スナップショット管理。スナップショットの作成
 a| 
VM の現在の状態からスナップショットを作成するために使用します。



|   a| 
仮想マシン.スナップショット管理.スナップショットの削除
 a| 
スナップショット履歴からスナップショットを削除するために使用します。



|   a| 
仮想マシン。スナップショット管理。スナップショットへの復元
 a| 
VM を特定のスナップショットの状態に設定する場合に使用します。

|===