---
sidebar: sidebar 
permalink: get-started/dr-setup.html 
keywords: bluexp, disaster recovery, aws, amazon web services, amazon fsx for netapp ontap 
summary: NetApp Disaster Recoveryを使用するには、いくつかの手順を実行してセットアップする必要があります。 
---
= NetApp Disaster Recovery用のインフラストラクチャをセットアップする
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
NetApp Disaster Recovery を使用するには、まず障害発生前に復旧環境を準備し、レプリケーションとフェイルオーバーを最小限の遅延で構成およびテストできるようにしておくことが重要です。


TIP: レビューlink:../get-started/dr-prerequisites.html["前提条件"]システムの準備ができていることを確認します。



[[supported-infrastructures]]
== サポートされているインフラストラクチャ

NetApp Disaster Recovery は、次のインフラストラクチャで使用できます。

* ハイブリッドクラウドディザスタリカバリは、オンプレミスの VMware と ONTAP データセンターを、VMware Cloud on AWS または Elastic VMware Service（EVS）および Amazon FSx for NetApp ONTAP に基づく AWS ディザスタリカバリインフラストラクチャにレプリケートします。
* オンプレミスのVMware と ONTAP の vCenter を別のオンプレミスのVMware と ONTAP の vCenter にレプリケートするプライベートクラウドのディザスタリカバリ。
* VMware Cloud on AWS または EVS に基づく AWS ディザスター リカバリ インフラストラクチャを、FSx for NetApp ONTAP を使用して別の AWS ベースのディザスター リカバリ インフラストラクチャに複製するクラウド ディザスター リカバリ。
* ハイブリッドクラウドディザスタリカバリは、オンプレミスのVMware と ONTAP データセンターを、Google Cloud VMware Engine と Google Cloud NetApp Volumes をベースとした Google のディザスタリカバリインフラストラクチャにレプリケートします。




[[hybrid-cloud-with-vmware-cloud-and-amazon-fsx-for-netapp-ontap]]
== VMware Cloud とAmazon FSx for NetApp ONTAPハイブリッド クラウド

この方法は、NFSプロトコルを使用するONTAP FlexVolボリューム上でホストされるデータストアを使用した、オンプレミスの本番vCenterインフラで構成されます。災害対策サイトは、NFSプロトコルを使用する1つ以上のFSx for ONTAPインスタンスによって提供されるFlexVolボリューム上でホストされるデータストアを使用した、1つ以上のVMware Cloud SDDCインスタンスで構成されます。

本番環境サイトと災害復旧サイトは、AWS互換のセキュアな接続で結ばれています。一般的な接続タイプとしては、セキュアなVPN（プライベートVPNまたはAWS提供のVPN）、AWS Direct Connect、またはその他の承認された相互接続方法などがあります。

AWS クラウド インフラストラクチャに関連する災害復旧の場合は、AWS のコンソール エージェントを使用する必要があります。エージェントは、FSx for ONTAPインスタンスと同じ VPC にインストールする必要があります。追加の FSx for ONTAPインスタンスが他の VPC に導入されている場合、エージェントをホストしている VPC は他の VPC にアクセスできる必要があります。



[[aws-availability-zones]]
=== AWSアベイラビリティゾーン

AWS は、リージョン内の 1 つまたは複数のアベイラビリティ ゾーン （AZ） にソリューションをデプロイすることをサポートしています。NetApp Disaster Recovery では、AWS でホストされている 2 つのサービス（VMware Cloud on AWS と Amazon FSx for NetApp ONTAP）を使用します。

* *VMware Cloud for AWS*：シングルAZまたはデュアルAZのストレッチクラスタSDDC環境へのデプロイをサポートします。NetApp Disaster Recovery は、VMware Cloud on AWS のシングルAZ SDDCデプロイのみをサポートします。
* *AWS FSx for NetApp ONTAP*：Amazon FSx for NetApp ONTAPがマルチAZ構成で導入されている場合、各ボリュームは1つのFSx for ONTAPファイルシステムによって所有され、データは2つ目のファイルシステムにミラーリングされます。FSx for ONTAPは、シングルAZ構成またはマルチAZ構成で導入できます。NetApp Disaster Recoveryは、両方の導入モデルをサポートしています。


*ベストプラクティス*：AWS 災害復旧サイト構成の場合、NetApp では、VMware Cloud と AWS FSx for ONTAP インスタンスの両方にシングル AZ デプロイメントを使用することを推奨します。AWS は災害復旧に使用されているため、複数のアベイラビリティゾーンを導入するメリットはありません。マルチ AZ デプロイメントは、コストと複雑さを増大させる可能性があります。



[[on-premises-to-aws]]
=== オンプレミスからAWSへ

AWS は、プライベートデータセンターを AWS クラウドに接続するための次の方法を提供します。各ソリューションには利点とコストに関する考慮事項があります。

* *AWS Direct Connect*：これは、お客様のプライベートデータセンターと同じ地理的エリアに設置され、AWSパートナーによって提供されるAWSクラウド相互接続サービスです。このソリューションは、公共のインターネット接続を必要とせずに、ローカルデータセンターとAWSクラウド間の安全でプライベートな接続を提供します。これはAWSが提供する最も直接的で効率的な接続方法です。
* *AWS インターネットゲートウェイ*: AWS クラウドリソースと外部コンピューティングリソース間のパブリック接続を提供します。このタイプの接続は通常、セキュリティが要求されない HTTP/HTTPS サービスなど、外部の顧客にサービスを提供するために使用されます。サービス品質の制御、セキュリティ、接続の保証はありません。このため、この接続方法は、実稼働データセンターをクラウドに接続する場合には推奨されません。
* *AWS Site-to-Site VPN*：この仮想プライベートネットワーク接続は、公共インターネットサービスプロバイダを介して安全な接続を提供します。VPN は、AWS クラウドとの間で送受信されるすべてのデータを暗号化および復号化します。VPN はソフトウェアベースまたはハードウェアベースのいずれかです。エンタープライズアプリケーションの場合、公共インターネットサービスプロバイダ（ISP）は、ディザスタリカバリレプリケーションに必要な帯域幅とレイテンシが確保されるよう、サービス品質保証を提供する必要があります。


*ベストプラクティス*： AWS災害復旧サイト構成の場合、NetApp は AWS Direct Connect の使用を推奨します。このソリューションは、エンタープライズアプリケーションに最高のパフォーマンスとセキュリティを提供します。利用できない場合は、ハイパフォーマンスな公共インターネットサービスプロバイダ（ISP）接続と VPN を併用する必要があります。ISP が適切なネットワークパフォーマンスを確保するための商用 QoS サービスレベルを提供していることを確認してください。



[[vpc-to-vpc-interconnections]]
=== VPC 間の相互接続

AWS では、次のタイプの VPC 間相互接続を提供しています。各ソリューションには利点とコストに関する考慮事項があります。

* *VPC ピアリング*: これは 2 つの VPC 間のプライベート接続です。これは AWS が提供する最も直接的で効率的な接続方法です。  VPC ピアリングを使用すると、同じまたは異なる AWS リージョン内の VPC を接続できます。
* *AWS インターネットゲートウェイ*: これは通常、AWS VPC リソースと AWS 以外のリソースおよびエンドポイント間の接続を提供するために使用されます。すべてのトラフィックは「ヘアピン」パスをたどります。このパスでは、別の VPC 宛ての VPC トラフィックがインターネットゲートウェイを介して AWS インフラストラクチャから出て、同じゲートウェイまたは別のゲートウェイを介して AWS インフラストラクチャに戻ります。これは、エンタープライズ VMware ソリューションに適した VPC 接続タイプではありません。
* *AWS Transit Gateway*: これは集中型のルーターベースの接続タイプであり、各 VPC が単一の中央ゲートウェイに接続できるようにします。このゲートウェイは、すべての VPC 間トラフィックの中央ハブとして機能します。これを VPN ソリューションに接続して、オンプレミスのデータセンター リソースが AWS VPC でホストされているリソースにアクセスできるようにすることもできます。このタイプの接続を実装するには、通常、追加のコストが必要です。


*ベストプラクティス*： VMware Cloud と単一の FSx for ONTAP VPC を使用するディザスタリカバリソリューションの場合、NetApp は VPC ピアリングの使用を推奨します。複数の FSx for ONTAP VPC をデプロイする場合は、複数の VPC ピア接続の管理オーバーヘッドを削減するために、AWS Transit Gateway の使用をお勧めします。



[[get-ready-for-on-premises-to-cloud-protection-using-aws]]
=== AWS を使用したオンプレミスからクラウドへの保護の準備

AWS を使用してオンプレミスからクラウドへの保護用にNetApp Disaster Recovery を設定するには、以下を設定する必要があります。

* NetApp ONTAP用の AWS FSx をセットアップする
* VMware Cloud on AWS SDDC をセットアップする




==== NetApp ONTAP用の AWS FSx をセットアップする

* Amazon FSx for NetApp ONTAPファイルシステムを作成します。
+
** FSx for ONTAPをプロビジョニングおよび構成します。  Amazon FSx for NetApp ONTAP は、 NetApp ONTAPファイルシステム上に構築された、信頼性が高く、スケーラブルで、高性能かつ機能豊富なファイルストレージを提供する、フルマネージドサービスです。
** 以下の手順に従ってください https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.html["テクニカルレポート 4938: VMware Cloud on AWS でAmazon FSx ONTAP をNFS データストアとしてマウントする"^]そして https://docs.netapp.com/us-en/storage-management-fsx-ontap/start/task-getting-started-fsx.html["Amazon FSx for NetApp ONTAP のクイックスタート"]FSx for ONTAPをプロビジョニングおよび構成します。


* Amazon FSx for ONTAPをシステムに追加し、 FSx for ONTAPの AWS 認証情報を追加します。
* AWS FSx for ONTAP インスタンスのデスティネーション ONTAP SVM を作成または確認します。
* NetApp Consoleで、ソースのオンプレミスONTAPクラスターと FSx for ONTAPインスタンス間のレプリケーションを構成します。


参照 https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html["FSx for ONTAPシステムのセットアップ方法"^]詳細な手順については、こちらをご覧ください。



==== VMware Cloud on AWS SDDC をセットアップする

https://www.vmware.com/products/vmc-on-aws.html["VMware Cloud on AWS"^]AWS エコシステム内の VMware ベースのワークロードにクラウドネイティブのエクスペリエンスを提供します。各 VMware ソフトウェア定義データセンター (SDDC) は Amazon Virtual Private Cloud (VPC) で実行され、完全な VMware スタック (vCenter Server を含む)、NSX-T ソフトウェア定義ネットワーク、vSAN ソフトウェア定義ストレージ、およびワークロードにコンピューティング リソースとストレージ リソースを提供する 1 つ以上の ESXi ホストを提供します。

AWS上でVMware Cloud環境を構成するには、以下の手順に従ってください。 https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html["AWS 上で仮想化環境を展開および構成する"^]パイロットライト クラスターは、災害復旧の目的にも使用できます。



[[private-cloud]]
== プライベート クラウド

NetApp Disaster Recoveryを使用すると、VM データストアを同じプライベート データセンター内またはリモートのプライベート データセンターまたは併置されたデータセンター内の別の vCenter クラスタに複製することで、1 つ以上の vCenter クラスタでホストされている VMware VM を保護できます。

オンプレミスからオンプレミスへの状況では、物理サイトの 1 つにコンソール エージェントをインストールします。

Disaster Recovery は、イーサネットと TCP/IP を使用したサイト間レプリケーションをサポートします。本番環境の仮想マシンにおけるデータ変更率に対応できる十分な帯域幅が確保されていることを確認し、すべての変更がリカバリポイント目標（RPO）時間内に災害復旧サイトにレプリケートされるようにしてください。



[[get-ready-for-on-premises-to-on-premises-protection]]
=== オンプレミスからオンプレミスへの保護の準備

オンプレミス間の保護のためにNetApp Disaster Recovery を設定する前に、次の要件が満たされていることを確認してください。

* ONTAPストレージ
+
** ONTAP認証情報があることを確認します。
** 災害復旧サイトを作成または検証します。
** 宛先のONTAP SVM を作成または検証します。
** ソースとデスティネーションのONTAP SVM がピアリングされていることを確認します。


* vCenter クラスタ
+
** 保護する VM が NFS データストア ( ONTAP NFS ボリュームを使用) または VMFS データストア ( NetApp iSCSI LUN を使用) でホストされていることを確認します。
** レビューlink:../reference/vcenter-privileges.html["vCenter 権限"]NetApp Disaster Recoveryに必要です。
** 災害復旧ユーザー アカウント (デフォルトの vCenter 管理者アカウントではない) を作成し、そのアカウントに vCenter 権限を割り当てます。






[[intelligent-proxy-support]]
=== インテリジェントなプロキシサポート

NetApp Consoleエージェントはインテリジェント プロキシをサポートします。インテリジェント プロキシは、オンプレミス環境をNetApp Consoleに接続するための軽量かつ安全で効率的な方法です。 VPN や直接のインターネット アクセスを必要とせずに、システムとコンソール サービス間の安全な接続を提供します。この最適化されたプロキシ実装は、ローカル ネットワーク内の API トラフィックをオフロードします。

プロキシが設定されている場合、 NetApp Disaster Recovery はVMware またはONTAPと直接通信を試み、直接通信が失敗した場合は設定されたプロキシを使用します。

NetApp Disaster Recovery プロキシの実装では、コンソールエージェントと任意の vCenter サーバーおよび ONTAP アレイ間で、HTTPS プロトコルを使用したポート 443 通信が必要です。コンソールエージェント内の NetApp Disaster Recovery エージェントは、アクションの実行時に VMware vSphere、vCenter サーバー、または ONTAP と直接通信します。

NetApp Consoleでの一般的なプロキシ設定の詳細については、以下を参照してください。 https://docs.netapp.com/us-en/console-setup-admin/task-configuring-proxy.html["プロキシサーバーを使用するようにコンソールエージェントを構成する"^] 。
