---
sidebar: sidebar 
permalink: get-started/reference-vmware-prerequisites.html 
keywords: vmware cluster prerequisites, vmware, vcenter, requirements 
summary: NetApp Disaster Recoveryを使用する前に、環境がVMware vCenterクラスタの要件を満たしていることを確認してください。 
---
= NetApp Disaster RecoveryにおけるVMware vCenterクラスタの前提条件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
NetApp Disaster Recoveryを使用する前に、環境がVMware vCenterクラスタの要件を満たしていることを確認してください。



[[general-prerequisites]]
== 一般的な前提条件

これらの前提条件は、オンプレミスの vCenter クラスタと VMware Cloud for AWS ソフトウェア定義データセンター (SDDC) の両方に適用されます。

* レビューlink:../reference/vcenter-privileges.html["vCenter 権限"]NetApp Disaster Recoveryに必要です。
* NetApp Disaster Recoveryで管理するすべての VMware クラスターは、保護する VM をホストするためにONTAPボリュームを使用します。
* NetApp Disaster Recoveryによって管理されるすべての VMware データストアでは、次のいずれかのプロトコルを使用する必要があります。
+
** NFS
** iSCSI または FC プロトコルを使用した VMFS


* VMware vSphere バージョン 7.0 Update 3 (7.0v3) 以降




[[vmware-cloud-sddc-prerequisites]]
== VMware Cloud SDDCの前提条件

VMware Cloud SDDC を使用する場合は、以下の追加の前提条件が適用されます。

* VMware Cloud コンソールでは、管理者および NSX Cloud 管理者のサービス ロールを使用します。組織ロールには組織の所有者も使用します。参照 https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/vmware-cloud-ontap.html["VMware Cloud Foundations と AWS FSx for NetApp ONTAP の使用に関するドキュメント"^]。
* VMware Cloud SDDC をAmazon FSx for NetApp ONTAPインスタンスにリンクします。参照 https://vmc.techzone.vmware.com/fsx-guide#overview["VMware Cloud on AWS とAmazon FSx for NetApp ONTAP の統合の展開情報"^]。

