---
sidebar: sidebar 
permalink: release-notes/dr-whats-new.html 
keywords: disaster recovery, bluexp, disaster recovery, vmware, vcenter, draas, disaster 
summary: NetApp Disaster Recovery は、災害復旧ワークフローを自動化するクラウドベースの災害復旧サービスです。  NetApp Disaster Recovery for VMware を使用すると、 ONTAPストレージを実行しているオンプレミスの VMware ワークロードを、 NetAppクラウド ストレージを使用して、災害復旧サイトとしてパブリック クラウド内の VMware ソフトウェア定義データセンターに複製できます。 
---
= NetApp Disaster Recoveryの新機能
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Disaster Recoveryの新機能について説明します。



== 2025年10月6日



=== BlueXP disaster recoveryはNetApp Disaster Recoveryになりました

BlueXP disaster recoveryはNetApp Disaster Recoveryに名前が変更されました。



=== BlueXPはNetApp Consoleになりました

NetApp Consoleは、強化され再構築されたBlueXP基盤上に構築され、オンプレミスとクラウド環境全体にわたるエンタープライズ グレードのNetAppストレージとNetApp Data Servicesの集中管理を提供し、リアルタイムの分析情報、より高速なワークフロー、および高度なセキュリティとコンプライアンスを備えた簡素化された管理を実現します。

変更内容の詳細については、link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetApp Consoleのリリースノート"] 。



=== その他のアップデート

* Amazon FSx for NetApp ONTAPを使用した Amazon Elastic VMware Service (EVS) のサポートはパブリックプレビュー段階です。このリリースにより、一般公開されました。詳細については、link:../reference/evs-deploy-guide-introduction.html["Amazon Elastic VMware Service とAmazon FSx for NetApp ONTAPを使用したNetApp Disaster Recoveryの紹介"] 。
* オンプレミス展開での検出時間の短縮を含む、ストレージ検出の改善
* ロールベースのアクセス制御（RBAC）や強化されたユーザー権限を含む、アイデンティティおよびアクセス管理（IAM）のサポート
* Azure VMware ソリューションとCloud Volumes ONTAPのプライベート プレビュー サポート。このサポートにより、 Cloud Volumes ONTAPストレージを使用して、オンプレミスから Azure VMware ソリューションへのディザスター リカバリー保護を構成できるようになりました。




== 2025年8月4日

バージョン4.2.5P2



=== NetApp Disaster Recoveryのアップデート

このリリースには次の更新が含まれています。

* 複数のストレージ仮想マシンから提示される同じ LUN を処理できるように VMFS サポートが改善されました。
* すでにアンマウントまたは削除されているデータストアを処理するために、テストのティアダウン クリーンアップが改善されました。
* サブネット マッピングが改善され、入力されたゲートウェイが指定されたネットワーク内に含まれているかどうかが検証されるようになりました。
* VM 名に「.com」が含まれている場合にレプリケーション プランが失敗する可能性がある問題を修正しました。
* レプリケーション プラン作成の一環としてボリュームを作成するときに、宛先ボリュームがソース ボリュームと同じになることを妨げる制限を削除しました。
* Azure Marketplace のNetApp Intelligent Services への従量課金制 (PAYGO) サブスクリプションのサポートが追加され、無料試用版ダイアログに Azure Marketplace へのリンクが追加されました。
+
詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html#licensing["NetApp Disaster Recoveryライセンス"]そして https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["NetApp Disaster Recoveryのライセンスを設定する"]。





== 2025年7月14日

バージョン4.2.5



=== NetApp Disaster Recoveryにおけるユーザーロール

NetApp Disaster Recoveryでは、各ユーザーの特定の機能やアクションへのアクセスを制御するためにロールを採用するようになりました。

このサービスは、NetApp Disaster Recoveryに固有の次のロールを使用します。

* *ディザスタ リカバリ管理者*: NetApp Disaster Recoveryであらゆるアクションを実行します。
* *災害復旧フェイルオーバー管理者*: NetApp Disaster Recoveryでフェイルオーバーと移行アクションを実行します。
* *災害復旧アプリケーション管理者*: レプリケーション プランを作成および変更し、テスト フェイルオーバーを開始します。
* *ディザスタ リカバリ ビューアー*: NetApp Disaster Recoveryの情報を表示できますが、アクションを実行することはできません。


NetApp Disaster Recoveryサービスをクリックして初めて構成する場合は、*SnapCenterAdmin* 権限または *Organization Admin* ロールが必要です。

詳細については、  https://docs.netapp.com/us-en/bluexp-disaster-recovery/reference/dr-reference-roles.html["NetApp Disaster Recoveryにおけるユーザーの役割と権限"] 。

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["すべてのサービスのアクセスロールについて学ぶ"^] 。



=== NetApp Disaster Recoveryのその他のアップデート

* 強化されたネットワーク検出
* スケーラビリティの改善:
+
** すべての詳細ではなく必要なメタデータをフィルタリングする
** VM リソースをより速く取得および更新するための検出の改善
** データ取得とデータ更新のためのメモリ最適化とパフォーマンス最適化
** vCenter SDK クライアントの作成とプール管理の改善


* 次回のスケジュールされた検出または手動検出時の古いデータの管理:
+
** vCenter で VM が削除されると、 NetApp Disaster Recoveryによってその VM がレプリケーション プランから自動的に削除されるようになりました。
** vCenter でデータストアまたはネットワークが削除されると、 NetApp Disaster Recoveryによってレプリケーション プランとリソース グループからそれが削除されるようになりました。
** vCenter でクラスタ、ホスト、またはデータセンターが削除されると、 NetApp Disaster Recoveryによってレプリケーション プランとリソース グループからそれが削除されるようになりました。


* ブラウザのシークレット モードで Swagger ドキュメントにアクセスできるようになりました。NetApp Disaster Recovery内の [設定] オプション > [API ドキュメント] からアクセスするか、ブラウザのシークレット モードで次の URL から直接アクセスできます。 https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["Swaggerドキュメント"^] 。
* 状況によっては、フェイルバック操作後に、操作の完了後に iGroup が残されることがあります。このアップデートでは、古くなった iGroup が削除されます。
* レプリケーション プランで NFS FQDN が使用されていた場合、 NetApp Disaster Recovery はそれを IP アドレスに解決するようになりました。この更新は、災害復旧サイトで FQDN を解決できない場合に役立ちます。
* UIの配置の改善
* 検出が成功した後に vCenter のサイズ設定の詳細をキャプチャするためのログの改善




== 2025年6月30日

バージョン4.2.4P2



=== 発見の改善

このアップデートにより検出プロセスが改善され、検出に必要な時間が短縮されます。



== 2025年6月23日

バージョン4.2.4P1



=== サブネットマッピングの改善

このアップデートでは、新しい検索機能によりサブネット マッピングの追加と編集ダイアログが強化されています。検索語を入力することで特定のサブネットをすばやく見つけることができるようになり、サブネット マッピングの管理が容易になりました。



== 2025年6月9日

バージョン4.2.4



=== Windows ローカル管理者パスワードソリューション (LAPS) のサポート

Windows ローカル管理者パスワード ソリューション (Windows LAPS) は、Active Directory 上のローカル管理者アカウントのパスワードを自動的に管理およびバックアップする Windows 機能です。

ドメイン コントローラーの詳細を指定して、サブネット マッピング オプションを選択し、LAPS オプションを確認できるようになりました。このオプションを使用すると、仮想マシンごとにパスワードを入力する必要がなくなります。

詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"] 。



== 2025年5月13日

バージョン4.2.3



=== サブネットマッピング

このリリースでは、サブネット マッピングを使用してフェイルオーバー時の IP アドレスを新しい方法で管理できるようになり、vCenter ごとにサブネットを追加できるようになりました。これを実行すると、各仮想ネットワークの IPv4 CIDR、デフォルト ゲートウェイ、および DNS が定義されます。

フェイルオーバー時に、 NetApp Disaster Recovery は、マッピングされた仮想ネットワークに提供された CIDR を調べて各 vNIC の適切な IP アドレスを決定し、それを使用して新しい IP アドレスを導出します。

例えば：

* ネットワークA = 10.1.1.0/24
* ネットワークB = 192.168.1.0/24


VM1 には、NetworkA に接続された vNIC (10.1.1.50) があります。レプリケーション プラン設定では、NetworkA は NetworkB にマップされます。

フェイルオーバー時に、 NetApp Disaster Recovery は元の IP アドレス (10.1.1) のネットワーク部分を置き換え、元の IP アドレス (10.1.1.50) のホスト アドレス (.50) を保持します。 VM1 の場合、 NetApp Disaster Recovery はNetworkB の CIDR 設定を確認し、NetworkB のネットワーク部分 192.168.1 を使用し、ホスト部分 (.50) を保持して VM1 の新しい IP アドレスを作成します。新しい IP は 192.168.1.50 になります。

要約すると、ホスト アドレスは同じままですが、ネットワーク アドレスはサイトのサブネット マッピングで構成されているものに置き換えられます。これにより、特に数百のネットワークと数千の VM を管理する場合に、フェイルオーバー時の IP アドレスの再割り当てをより簡単に管理できるようになります。

サイトにサブネットマッピングを含める方法の詳細については、以下を参照してください。 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["vCenter Server サイトを追加する"] 。



=== スキップ保護

レプリケーション プランのフェイルオーバー後にサービスが自動的に逆保護関係を作成しないように、保護をスキップできるようになりました。これは、NetApp Disaster Recovery内でサイトをオンラインに戻す前に、復元されたサイトで追加の操作を実行する場合に役立ちます。

フェールオーバーを開始すると、元のソース サイトがオンラインの場合、デフォルトでは、サービスによってレプリケーション プラン内の各ボリュームに対して逆方向の保護関係が自動的に作成されます。これは、サービスがターゲット サイトからソース サイトへのSnapMirror関係を作成することを意味します。また、フェイルバックを開始すると、このサービスはSnapMirror関係を自動的に元に戻します。

フェイルオーバーを開始するときに、*保護をスキップ*オプションを選択できるようになりました。これにより、サービスはSnapMirror関係を自動的に逆転させなくなります。代わりに、レプリケーション プランの両側に書き込み可能なボリュームを残します。

元のソース サイトがオンラインに戻った後、レプリケーション プランの [アクション] メニューから [*リソースの保護*] を選択して、逆方向の保護を確立できます。これにより、プラン内の各ボリュームに対して逆方向のレプリケーション関係を作成しようとします。保護が復元されるまで、このジョブを繰り返し実行できます。保護が復元されると、通常の方法でフェイルバックを開始できます。

スキップ保護の詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["アプリケーションをリモートサイトにフェイルオーバーする"] 。



=== SnapMirrorはレプリケーションプランで更新をスケジュールします

NetApp Disaster Recovery、ネイティブのONTAP SnapMirrorポリシー スケジューラやONTAPとのサードパーティ統合などの外部スナップショット管理ソリューションの使用がサポートされるようになりました。レプリケーション プラン内のすべてのデータストア (ボリューム) に、別の場所で管理されているSnapMirror関係がすでに存在する場合は、それらのスナップショットをNetApp Disaster Recoveryのリカバリ ポイントとして使用できます。

設定するには、レプリケーション プラン > リソース マッピング セクションで、データストア マッピングを設定するときに *プラットフォーム管理のバックアップと保持スケジュールを使用する* チェックボックスをオンにします。

このオプションを選択すると、 NetApp Disaster Recovery はバックアップ スケジュールを構成しません。ただし、テスト、フェイルオーバー、フェイルバック操作のためにスナップショットが作成される可能性があるため、保持スケジュールを構成する必要があります。

これが構成されると、サービスは定期的にスケジュールされたスナップショットを取得せず、代わりに外部エンティティに依存してスナップショットを取得および更新します。

レプリケーションプランで外部スナップショットソリューションを使用する方法の詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"] 。



== 2025年4月16日

バージョン4.2.2



=== VMのスケジュールされた検出

NetApp Disaster Recovery は24 時間ごとに検出を実行します。このリリースでは、ニーズに合わせて検出スケジュールをカスタマイズし、必要なときにパフォーマンスへの影響を軽減できるようになりました。たとえば、多数の VM がある場合は、検出スケジュールを 48 時間ごとに実行するように設定できます。  VM の数が少ない場合は、検出スケジュールを 12 時間ごとに実行するように設定できます。

検出をスケジュールしたくない場合は、スケジュールされた検出オプションを無効にして、いつでも手動で検出を更新できます。

詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["vCenter Server サイトを追加する"] 。



=== リソース グループ データストアのサポート

以前は、VM ごとにのみリソース グループを作成できました。このリリースでは、データストアごとにリソース グループを作成できるようになりました。レプリケーション プランを作成し、そのプランのリソース グループを作成すると、データストア内のすべての VM が一覧表示されます。これは、多数の VM があり、それらをデータストアごとにグループ化したい場合に便利です。

次の方法で、データストアを含むリソース グループを作成できます。

* データストアを使用してリソース グループを追加する場合は、データストアの一覧を表示できます。  1 つ以上のデータストアを選択してリソース グループを作成できます。
* レプリケーション プランを作成し、プラン内にリソース グループを作成すると、データストア内の VM を確認できます。


詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"] 。



=== 無料トライアルまたはライセンスの有効期限の通知

このリリースでは、ライセンスを取得する時間を確保するために、無料トライアルが 60 日後に期限切れになることを通知します。このリリースでは、ライセンスの有効期限が切れる日に通知も提供されます。



=== サービス更新の通知

このリリースでは、サービスがアップグレードされ、メンテナンス モードになっていることを示すバナーが上部に表示されます。バナーは、サービスのアップグレード中に表示され、アップグレードが完了すると消えます。アップグレードの進行中も UI での作業は続行できますが、新しいジョブを送信することはできません。更新が完了し、サービスが本番モードに戻った後に、スケジュールされたジョブが実行されます。



== 2025年3月10日

バージョン4.2.1



=== インテリジェントなプロキシサポート

NetApp Consoleエージェントはインテリジェント プロキシをサポートします。インテリジェント プロキシは、オンプレミス システムをNetApp Disaster Recoveryに接続するための軽量かつ安全で効率的な方法です。 VPN や直接のインターネット アクセスを必要とせずに、システムとNetApp Disaster Recovery間の安全な接続を提供します。この最適化されたプロキシ実装は、ローカル ネットワーク内の API トラフィックをオフロードします。

プロキシが設定されている場合、 NetApp Disaster Recovery はVMware またはONTAPと直接通信を試み、直接通信が失敗した場合は設定されたプロキシを使用します。

NetApp Disaster Recoveryプロキシの実装では、コンソール エージェントと、HTTPS プロトコルを使用した vCenter Server およびONTAPアレイ間のポート 443 通信が必要です。コンソール エージェント内のNetApp Disaster Recoveryエージェントは、アクションを実行するときに VMware vSphere、VC、またはONTAPと直接通信します。

NetApp Disaster Recoveryのインテリジェントプロキシの詳細については、以下を参照してください。 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-setup.html["NetApp Disaster Recovery用のインフラストラクチャをセットアップする"] 。

NetApp Consoleでの一般的なプロキシ設定の詳細については、以下を参照してください。 https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["プロキシサーバーを使用するようにコンソールエージェントを構成する"^] 。



=== 無料トライアルはいつでも終了できます

無料トライアルはいつでも停止できます。また、有効期限が切れるまで待つこともできます。

見る https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html#end-the-free-trial["無料トライアルを終了する"]。



== 2025年2月19日

バージョン4.2



=== VMFSストレージ上のVMおよびデータストアに対するASA r2のサポート

NetApp Disaster Recoveryのこのリリースでは、VM および VMFS ストレージ上のデータストアに対してASA r2 のサポートが提供されます。  ASA r2 システムでは、 ONTAPソフトウェアは基本的な SAN 機能をサポートしますが、SAN 環境でサポートされていない機能は削除されます。

このリリースでは、 ASA r2 の次の機能がサポートされています。

* プライマリ ストレージの整合性グループのプロビジョニング (フラットな整合性グループのみ、つまり階層構造のない 1 つのレベルのみ)
* SnapMirror自動化を含むバックアップ（コンシステンシグループ）操作


NetApp Disaster RecoveryにおけるASA r2 のサポートには、 ONTAP 9.16.1 が使用されます。

データストアはONTAPボリュームまたはASA r2 ストレージ ユニットにマウントできますが、 NetApp Disaster Recoveryのリソース グループにはONTAPのデータストアとASA r2 のデータストアの両方を含めることはできません。リソース グループでは、 ONTAPのデータストアまたはASA r2 のデータストアのいずれかを選択できます。



== 2024年10月30日



=== レポート

ランドスケープの分析に役立つレポートを生成してダウンロードできるようになりました。事前に設計されたレポートでは、フェイルオーバーとフェイルバックの概要、すべてのサイトのレプリケーションの詳細、過去 7 日間のジョブの詳細が表示されます。

参照 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/reports.html["災害復旧レポートを作成する"]。



=== 30日間無料トライアル

NetApp Disaster Recoveryの 30 日間無料トライアルに今すぐサインアップできます。以前は、無料トライアルは 90 日間でした。

参照 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["ライセンスの設定"]。



=== レプリケーションプランの無効化と有効化

以前のリリースには、日次および週次スケジュールをサポートするために必要だったフェールオーバー テスト スケジュール構造の更新が含まれていました。この更新では、新しい毎日および毎週のフェールオーバー テスト スケジュールを使用できるように、既存のすべてのレプリケーション プランを無効にしてから再度有効にする必要がありました。これは 1 回限りの要件です。

方法は次のとおりです。

. メニューから*レプリケーション プラン*を選択します。
. プランを選択し、[アクション] アイコンを選択してドロップダウン メニューを表示します。
. *無効*を選択します。
. 数分後、「*有効*」を選択します。




=== フォルダマッピング

レプリケーション プランを作成し、コンピューティング リソースをマップするときに、データセンター、クラスター、ホストに指定したフォルダーに VM が回復されるようにフォルダーをマップできるようになりました。

詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"] 。



=== フェイルオーバー、フェイルバック、テストフェイルオーバーに利用可能な VM の詳細

障害が発生し、フェイルオーバーを開始したり、フェイルバックを実行したり、フェイルオーバーをテストしたりするときに、VM の詳細を表示して、再起動しなかった VM を特定できるようになりました。

参照 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["アプリケーションをリモートサイトにフェイルオーバーする"]。



=== 順序付けられたブートシーケンスによる VM ブート遅延

レプリケーション プランを作成するときに、プラン内の各 VM のブート遅延を設定できるようになりました。これにより、VM の起動シーケンスを設定して、後続の優先度の VM が起動される前に、優先度 1 の VM がすべて実行されていることを確認できます。

詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"] 。



=== VM オペレーティング システム情報

レプリケーション プランを作成すると、プラン内の各 VM のオペレーティング システムを確認できるようになりました。これは、VM をリソース グループにグループ化する方法を決定するのに役立ちます。

詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"] 。



=== VM名のエイリアシング

レプリケーション プランを作成するときに、災害復旧サイトの VM 名にプレフィックスとサフィックスを追加できるようになりました。これにより、プラン内の VM に、より説明的な名前を使用できるようになります。

詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"] 。



=== 古いスナップショットをクリーンアップする

指定した保持数を超えて不要になったスナップショットは削除できます。スナップショットの保持数を減らすと、時間の経過とともにスナップショットが蓄積される可能性があります。これで、スナップショットを削除してスペースを解放できます。これは、オンデマンドでいつでも、またはレプリケーション プランを削除するときに実行できます。

詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["サイト、リソース グループ、レプリケーション プラン、データストア、仮想マシンの情報の管理"] 。



=== スナップショットを調整する

ソースとターゲット間で同期されていないスナップショットを調整できるようになりました。これは、NetApp Disaster Recoveryの外部のターゲットでスナップショットが削除された場合に発生する可能性があります。サービスは、ソース上のスナップショットを 24 時間ごとに自動的に削除します。ただし、これをオンデマンドで実行できます。この機能により、すべてのサイト間でスナップショットの一貫性を確保できます。

詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["レプリケーションプランの管理"] 。



== 2024年9月20日



=== オンプレミスからオンプレミスへの VMware VMFS データストアのサポート

このリリースには、オンプレミス ストレージに保護された iSCSI および FC 用の VMware vSphere 仮想マシン ファイル システム (VMFS) データストアにマウントされた VM のサポートが含まれています。以前は、このサービスは、iSCSI および FC 用の VMFS データストアをサポートする _テクノロジー プレビュー_ を提供していました。

iSCSI プロトコルと FC プロトコルの両方に関する追加の考慮事項を次に示します。

* FC サポートは、レプリケーション用ではなく、クライアント フロントエンド プロトコル用です。
* NetApp Disaster Recovery、 ONTAPボリュームごとに 1 つの LUN のみをサポートします。ボリュームには複数の LUN を含めることはできません。
* どのレプリケーション プランでも、宛先ONTAPボリュームは、保護された VM をホストするソースONTAPボリュームと同じプロトコルを使用する必要があります。たとえば、ソースが FC プロトコルを使用する場合、宛先も FC を使用する必要があります。




== 2024年8月2日



=== FC 向けオンプレミスからオンプレミスへの VMware VMFS データストアのサポート

このリリースには、オンプレミス ストレージに保護された FC 用の VMware vSphere 仮想マシン ファイル システム (VMFS) データストアにマウントされた VM のサポートの _テクノロジ プレビュー_ が含まれています。以前は、このサービスは iSCSI 用の VMFS データストアをサポートするテクノロジ プレビューを提供していました。


NOTE: NetApp は、プレビューされたワークロード容量に対して料金を請求しません。



=== ジョブのキャンセル

このリリースでは、ジョブ モニター UI でジョブをキャンセルできるようになりました。

参照 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["ジョブの監視"]。



== 2024年7月17日



=== フェイルオーバーテストスケジュール

このリリースには、日次および週次スケジュールをサポートするために必要だったフェールオーバー テスト スケジュール構造の更新が含まれています。この更新では、新しい毎日および毎週のフェールオーバー テスト スケジュールを使用できるように、既存のすべてのレプリケーション プランを無効にしてから再度有効にする必要があります。これは 1 回限りの要件です。

方法は次のとおりです。

. メニューから*レプリケーション プラン*を選択します。
. プランを選択し、[アクション] アイコンを選択してドロップダウン メニューを表示します。
. *無効*を選択します。
. 数分後、「*有効*」を選択します。




=== レプリケーションプランの更新

このリリースには、レプリケーション プラン データの更新が含まれており、「スナップショットが見つかりません」という問題が解決されています。これには、すべてのレプリケーション プランの保持数を 1 に変更し、オンデマンド スナップショットを開始する必要があります。このプロセスにより、新しいバックアップが作成され、古いバックアップはすべて削除されます。

方法は次のとおりです。

. メニューから*レプリケーション プラン*を選択します。
. レプリケーション プランを選択し、[*フェールオーバー マッピング*] タブを選択して、[*編集*] 鉛筆アイコンを選択します。
. *データストア*矢印を選択して展開します。
. レプリケーション プランの保持カウントの値をメモします。これらの手順が完了したら、この元の値を復元する必要があります。
. カウントを 1 に減らします。
. オンデマンド スナップショットを開始します。これを行うには、[レプリケーション プラン] ページでプランを選択し、[アクション] アイコンを選択して、[*今すぐスナップショットを作成*] を選択します。
. スナップショット ジョブが正常に完了したら、レプリケーション プランのカウントを、最初の手順でメモした元の値に戻します。
. 既存のすべてのレプリケーション プランに対してこれらの手順を繰り返します。




== 2024年7月5日

このNetApp Disaster Recoveryリリースには、次の更新が含まれています。



=== AFF Aシリーズのサポート

このリリースでは、 NetApp AFF A シリーズ ハードウェア プラットフォームがサポートされています。



=== オンプレミスからオンプレミスへの VMware VMFS データストアのサポート

このリリースには、オンプレミス ストレージに保護された VMware vSphere 仮想マシン ファイル システム (VMFS) データストアにマウントされた VM のサポートの _テクノロジ プレビュー_ が含まれています。このリリースでは、オンプレミスの VMware ワークロードから VMFS データストアを備えたオンプレミスの VMware 環境への災害復旧がテクノロジー プレビューでサポートされます。


NOTE: NetApp は、プレビューされたワークロード容量に対して料金を請求しません。



=== レプリケーションプランの更新

アプリケーション ページでデータストア別に VM をフィルタリングし、リソース マッピング ページでターゲットの詳細を選択することにより、レプリケーション プランをより簡単に追加できます。参照 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"]。



=== レプリケーションプランを編集する

このリリースでは、フェイルオーバー マッピング ページが強化され、よりわかりやすくなりました。

参照 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["プランを管理する"]。



=== VMを編集する

このリリースでは、プラン内の VM を編集するプロセスに、いくつかの小さな UI の改善が加えられました。

参照 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["VMを管理する"]。



=== フェイルオーバー更新

フェイルオーバーを開始する前に、VM のステータスと、VM の電源がオンかオフかを確認できるようになりました。フェイルオーバー プロセスでは、今すぐスナップショットを作成したり、スナップショットを選択したりできるようになりました。

参照 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["アプリケーションをリモートサイトにフェイルオーバーする"]。



=== フェイルオーバーテストスケジュール

フェールオーバー テストを編集し、フェールオーバー テストの日次、週次、月次スケジュールを設定できるようになりました。

参照 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["プランを管理する"]。



=== 前提条件情報の更新

NetApp Disaster Recovery の前提条件情報が更新されました。

参照 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-prerequisites.html["NetApp Disaster Recoveryの前提条件"]。



== 2024年5月15日

このNetApp Disaster Recoveryリリースには、次の更新が含まれています。



=== VMware ワークロードをオンプレミスからオンプレミスに複製する

これは一般提供機能としてリリースされました。以前は、機能が制限されたテクノロジ プレビューでした。



=== ライセンスの更新

NetApp Disaster Recoveryでは、90 日間の無料トライアルにサインアップしたり、Amazon Marketplace で従量課金制 (PAYGO) サブスクリプションを購入したり、NetApp の営業担当者またはNetAppサポート サイト (NSS) から取得したNetAppライセンス ファイル (NLF) である Bring Your NetApp License (BYOL) を使用したりすることができます。

NetApp Disaster Recoveryのライセンス設定の詳細については、以下を参照してください。link:../get-started/dr-licensing.html["ライセンスの設定"] 。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["NetApp Disaster Recoveryの詳細"] 。



== 2024年3月5日

これはNetApp Disaster Recoveryの一般提供リリースであり、次の更新が含まれています。



=== ライセンスの更新

NetApp Disaster Recoveryでは、90 日間の無料トライアルにサインアップするか、 NetApp の営業担当者から取得したNetAppライセンス ファイル (NLF) である Bring Your Own License (BYOL) を使用することができます。ライセンス シリアル番号を使用して、 NetApp Consoleサブスクリプションで BYOL をアクティブ化できます。  NetApp Disaster Recovery料金は、データストアのプロビジョニングされた容量に基づいて決まります。

NetApp Disaster Recoveryのライセンス設定の詳細については、以下を参照してください。 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["ライセンスの設定"] 。

すべてのNetApp Consoleデータサービスのライセンス管理の詳細については、 https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["すべてのNetApp Consoleデータサービスのライセンスを管理する"^] 。



=== スケジュールを編集する

このリリースでは、コンプライアンス テストとフェイルオーバー テストのスケジュールを設定して、必要に応じて正しく動作することを確認できるようになりました。

詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"] 。



== 2024年2月1日

このNetApp Disaster Recoveryプレビュー リリースには、次の更新が含まれています。



=== ネットワークの強化

このリリースでは、VM の CPU と RAM の値のサイズを変更できるようになりました。また、VM のネットワーク DHCP または静的 IP アドレスを選択することもできます。

* DHCP: このオプションを選択した場合は、VM の資格情報を提供します。
* 静的 IP: ソース VM と同じ情報または異なる情報を選択できます。ソースと同じものを選択した場合は、資格情報を入力する必要はありません。一方、ソースとは異なる情報を使用する場合は、資格情報、IP アドレス、サブネット マスク、DNS、ゲートウェイ情報を提供できます。


詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"] 。



=== カスタムスクリプト

フェイルオーバー後のプロセスとして含めることができるようになりました。カスタム スクリプトを使用すると、フェイルオーバー プロセス後にNetApp Disaster Recoveryでスクリプトを実行できます。たとえば、カスタム スクリプトを使用して、フェイルオーバーが完了した後にすべてのデータベース トランザクションを再開できます。

詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["リモートサイトへのフェイルオーバー"] 。



=== SnapMirror関係

レプリケーション プランを開発しながらSnapMirror関係を作成できるようになりました。以前は、 NetApp Disaster Recoveryの外部で関係を作成する必要がありました。

詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"] 。



=== 一貫性グループ

レプリケーション プランを作成するときに、異なるボリュームおよび異なる SVM からの VM を含めることができます。  NetApp Disaster Recovery は、すべてのボリュームを含めて整合性グループのスナップショットを作成し、すべてのセカンダリ ロケーションを更新します。

詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"] 。



=== VM電源オン遅延オプション

レプリケーション プランを作成するときに、リソース グループに VM を追加できます。リソース グループを使用すると、各 VM に遅延を設定して、遅延されたシーケンスで VM の電源をオンにすることができます。

詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"] 。



=== アプリケーション整合性のあるスナップショットコピー

アプリケーション整合性のあるスナップショット コピーを作成するように指定できます。サービスはアプリケーションを静止させ、スナップショットを取得してアプリケーションの一貫した状態を取得します。

詳細については、 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"] 。



== 2024年1月11日

NetApp Disaster Recoveryのこのプレビュー リリースには、次の更新が含まれています。



=== ダッシュボードをより速く

このリリースでは、ダッシュボードから他のページの情報にさらに迅速にアクセスできるようになりました。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["NetApp Disaster Recoveryについて学ぶ"] 。



== 2023年10月20日

NetApp Disaster Recoveryのこのプレビュー リリースには、次の更新が含まれています。



=== オンプレミスの NFS ベースの VMware ワークロードを保護する

NetApp Disaster Recovery を使用すると、パブリック クラウドに加えて、オンプレミスの NFS ベースの VMware 環境を別のオンプレミスの NFS ベースの VMware 環境への災害から保護できるようになります。  NetApp Disaster Recovery は、災害復旧計画の完了を調整します。


NOTE: このプレビュー オファリングでは、 NetApp は一般提供開始前にオファリングの詳細、内容、およびタイムラインを変更する権利を留保します。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["NetApp Disaster Recoveryの詳細"] 。



== 2023年9月27日

NetApp Disaster Recoveryのこのプレビュー リリースには、次の更新が含まれています。



=== ダッシュボードの更新

ダッシュボードのオプションを選択できるようになり、情報をすばやく簡単に確認できるようになりました。また、ダッシュボードにはフェイルオーバーと移行のステータスが表示されるようになりました。

参照 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/dashboard-view.html["ダッシュボードで災害復旧計画の健全性を確認する"]。



=== レプリケーションプランの更新

* *RPO*: レプリケーション プランのデータストア セクションで、復旧ポイント目標 (RPO) と保持数を入力できるようになりました。これは、設定された時間よりも古くない、存在する必要があるデータの量を示します。たとえば、これを 5 分に設定すると、災害が発生した場合にシステムが最大 5 分間のデータを失っても、ビジネスクリティカルなニーズには影響しません。
+
参照 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"]。

* *ネットワークの機能強化*: レプリケーション プランの仮想マシン セクションでソースとターゲットの場所の間でネットワークをマッピングするときに、 NetApp Disaster RecoveryDHCP または静的 IP の 2 つのオプションが提供されるようになりました。以前は、DHCP のみがサポートされていました。静的 IP の場合は、サブネット、ゲートウェイ、および DNS サーバーを構成します。さらに、仮想マシンの資格情報を入力できるようになりました。
+
参照 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"]。

* *スケジュールの編集*: レプリケーション プランのスケジュールを更新できるようになりました。
+
参照 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["リソースを管理する"]。

* * SnapMirror の自動化*: このリリースでレプリケーション プランを作成するときに、次のいずれかの構成でソース ボリュームとターゲット ボリューム間のSnapMirror関係を定義できます。
+
** 1～1
** ファンアウトアーキテクチャにおける1対多
** 一貫性グループとしての多対1
** 多対多
+
参照 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"]。







== 2023年8月1日



=== NetApp Disaster Recoveryプレビュー

NetApp Disaster Recoveryプレビューは、災害復旧ワークフローを自動化するクラウドベースの災害復旧サービスです。最初に、 NetApp Disaster Recoveryプレビューを使用すると、 Amazon FSx for ONTAPを使用して、 NetAppストレージを実行しているオンプレミスの NFS ベースの VMware ワークロードを AWS 上の VMware Cloud (VMC) に保護できます。


NOTE: このプレビュー オファリングでは、 NetApp は一般提供開始前にオファリングの詳細、内容、およびタイムラインを変更する権利を留保します。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["NetApp Disaster Recoveryの詳細"] 。

このリリースには次の更新が含まれています。



=== ブート順序のリソース グループの更新

災害復旧またはレプリケーション プランを作成するときに、機能リソース グループに仮想マシンを追加できます。リソース グループを使用すると、依存関係にある仮想マシンのセットを、要件を満たす論理グループにまとめることができます。たとえば、グループには回復時に実行できるブート順序を含めることができます。このリリースでは、各リソース グループに 1 つ以上の仮想マシンを含めることができます。仮想マシンは、プランに含めた順序に基づいて電源がオンになります。参照 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html#select-applications-to-replicate-and-assign-resource-groups["複製するアプリケーションを選択し、リソース グループを割り当てます"]。



=== レプリケーション検証

災害復旧またはレプリケーション プランを作成し、ウィザードで繰り返しを指定して、災害復旧サイトへのレプリケーションを開始すると、 NetApp Disaster Recovery は30 分ごとに、レプリケーションがプランに従って実際に実行されているかどうかを確認します。ジョブ モニター ページで進行状況を監視できます。。  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/replicate.html["アプリケーションを別のサイトに複製する"] 。



=== レプリケーション計画は、リカバリポイント目標（RPO）の転送スケジュールを示します。

災害復旧またはレプリケーション プランを作成するときに、VM を選択します。このリリースでは、データストアまたは VM に関連付けられている各ボリュームに関連付けられているSnapMirror を表示できるようになりました。SnapMirrorスケジュールに関連付けられている RPO 転送スケジュールも表示できます。RPO は、災害後の復旧にバックアップ スケジュールが十分かどうかを判断するのに役立ちます。参照 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"]。



=== ジョブモニターの更新

ジョブ モニター ページに更新オプションが追加され、操作の最新ステータスを取得できるようになりました。。  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["災害復旧ジョブを監視する"] 。



== 2023年5月18日

これはNetApp Disaster Recoveryの最初のリリースです。



=== クラウドベースの災害復旧サービス

NetApp Disaster Recovery は、災害復旧ワークフローを自動化するクラウドベースの災害復旧サービスです。最初に、 NetApp Disaster Recoveryプレビューを使用すると、 Amazon FSx for ONTAPを使用して、 NetAppストレージを実行しているオンプレミスの NFS ベースの VMware ワークロードを AWS 上の VMware Cloud (VMC) に保護できます。

link:https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["NetApp Disaster Recoveryの詳細"] 。
